<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\Jadwal;
use App\Models\Kelas;
use App\Models\Mapel;
use App\Models\Guru;
class JadwalSeeder extends Seeder
{
    public function run(): void
    {
        $jadwalPerKelasSmp = [
            '7' => [
                'Senin' => [
                    ['mapel' => 'DHUHA', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:00', 'end' => '07:30'],
                    ['mapel' => 'UPCR_SMP', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:30', 'end' => '08:15'],
                    ['mapel' => 'PJOK', 'guru' => 'Riva Riana, S.Pd', 'start' => '08:15', 'end' => '08:55'],
                    ['mapel' => 'PJOK', 'guru' => 'Riva Riana, S.Pd', 'start' => '08:55', 'end' => '09:35'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '09:35', 'end' => '09:50'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '09:50', 'end' => '10:30'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '10:30', 'end' => '11:10'],
                    ['mapel' => 'ING', 'guru' => 'Irnika Widiyan Dini, S.Li', 'start' => '11:10', 'end' => '11:50'],
                    ['mapel' => 'DZH', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:50', 'end' => '12:30'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '12:30', 'end' => '13:00'],
                    ['mapel' => 'ING', 'guru' => 'Irnika Widiyan Dini, S.Li', 'start' => '13:00', 'end' => '13:40'],
                    ['mapel' => 'IPS', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '13:40', 'end' => '14:20'],
                    ['mapel' => 'IPS', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '14:20', 'end' => '15:00'],
                    ['mapel' => 'BTQ', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '15:00', 'end' => '15:20'],
                    ['mapel' => 'ASHR_SMP', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '15:20', 'end' => '15:30'],
                ],
                'Selasa' => [
                    ['mapel' => 'DHUHA', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:00', 'end' => '07:30'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '07:30', 'end' => '08:10'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '08:10', 'end' => '08:50'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '08:50', 'end' => '09:05'],
                    ['mapel' => 'AQD', 'guru' => 'Nurhayati, S.Ag', 'start' => '09:05', 'end' => '09:45'],
                    ['mapel' => 'AQD', 'guru' => 'Nurhayati, S.Ag', 'start' => '09:45', 'end' => '10:25'],
                    ['mapel' => 'MTK', 'guru' => 'Ajeng Putyri Aryantika, S.Pd', 'start' => '10:25', 'end' => '11:05'],
                    ['mapel' => 'MTK', 'guru' => 'Ajeng Putyri Aryantika, S.Pd', 'start' => '11:05', 'end' => '11:45'],
                    ['mapel' => 'DZH', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:45', 'end' => '12:30'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '12:30', 'end' => '13:00'],
                    ['mapel' => 'ING', 'guru' => 'Irnika Widiyan Dini, S.Li', 'start' => '13:00', 'end' => '13:40'],
                    ['mapel' => 'B.IND', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '13:40', 'end' => '14:20'],
                    ['mapel' => 'B.IND', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '14:20', 'end' => '15:00'],
                    ['mapel' => 'BTQ', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '15:00', 'end' => '15:20'],
                    ['mapel' => 'ASHR_SMP', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '15:20', 'end' => '15:30'],
                ],
                'Rabu' => [
                    ['mapel' => 'DHUHA', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:00', 'end' => '07:30'],
                    ['mapel' => 'PRM', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:30', 'end' => '09:00'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '09:00', 'end' => '09:15'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '09:15', 'end' => '09:55'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '09:55', 'end' => '10:35'],
                    ['mapel' => 'ARB', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '10:35', 'end' => '11:15'],
                    ['mapel' => 'ARB', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '11:15', 'end' => '11:55'],
                    ['mapel' => 'DZH', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:55', 'end' => '12:30'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '12:30', 'end' => '13:00'],
                    ['mapel' => 'IPA', 'guru' => 'Riva Riana, S.Pd', 'start' => '13:00', 'end' => '13:40'],
                    ['mapel' => 'PBL', 'guru' => 'Vika Wati Dzulciha, S.Ag', 'start' => '13:40', 'end' => '14:20'],
                    ['mapel' => 'PBL', 'guru' => 'Vika Wati Dzulciha, S.Ag', 'start' => '14:20', 'end' => '15:00'],
                    ['mapel' => 'BTQ', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '15:00', 'end' => '15:20'],
                    ['mapel' => 'ASHR_SMP', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '15:20', 'end' => '15:30'],
                ],
                'Kamis' => [
                    ['mapel' => 'DHUHA', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:00', 'end' => '07:30'],
                    ['mapel' => 'IPA', 'guru' => 'Riva Riana, S.Pd', 'start' => '07:30', 'end' => '08:10'],
                    ['mapel' => 'IPA', 'guru' => 'Riva Riana, S.Pd', 'start' => '08:10', 'end' => '08:50'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '08:50', 'end' => '09:05'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '09:05', 'end' => '09:45'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '09:45', 'end' => '10:25'],
                    ['mapel' => 'FQH', 'guru' => 'Nurhayati, S.Ag', 'start' => '10:25', 'end' => '11:05'],
                    ['mapel' => 'FQH', 'guru' => 'Nurhayati, S.Ag', 'start' => '11:05', 'end' => '11:45'],
                    ['mapel' => 'DZH', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:45', 'end' => '12:30'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '12:30', 'end' => '13:00'],
                    ['mapel' => 'ING', 'guru' => 'Irnika Widiyan Dini, S.Li', 'start' => '13:00', 'end' => '13:40'],
                    ['mapel' => 'B.IND', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '13:40', 'end' => '14:20'],
                    ['mapel' => 'B.IND', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '14:20', 'end' => '15:00'],
                    ['mapel' => 'BTQ', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '15:00', 'end' => '15:20'],
                    ['mapel' => 'ASHR_SMP', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '15:20', 'end' => '15:30'],
                ],
                'Jumat' => [
                    ['mapel' => 'DHUHA', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:00', 'end' => '07:30'],
                    ['mapel' => 'BPI', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:30', 'end' => '08:30'],
                    ['mapel' => 'MTK', 'guru' => 'Ajeng Putyri Aryantika, S.Pd', 'start' => '08:30', 'end' => '09:10'],
                    ['mapel' => 'MTK', 'guru' => 'Ajeng Putyri Aryantika, S.Pd', 'start' => '09:10', 'end' => '09:50'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '09:50', 'end' => '10:05'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '10:05', 'end' => '10:45'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '10:45', 'end' => '11:15'],
                    ['mapel' => 'DZH', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:15', 'end' => '11:30'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:30', 'end' => '13:00'],
                    ['mapel' => 'TKD', 'guru' => 'Riva Riana, S.Pd', 'start' => '13:00', 'end' => '13:40'],
                    ['mapel' => 'TKD', 'guru' => 'Riva Riana, S.Pd', 'start' => '13:40', 'end' => '14:20'],
                ],
            ],
            '8A' => [
                'Senin' => [
                    ['mapel' => 'DHUHA', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:00', 'end' => '07:30'],
                    ['mapel' => 'UPCR_SMP', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:30', 'end' => '08:15'],
                    ['mapel' => 'MTK', 'guru' => 'Ajeng Putyri Aryantika, S.Pd', 'start' => '08:15', 'end' => '08:55'],
                    ['mapel' => 'MTK', 'guru' => 'Ajeng Putyri Aryantika, S.Pd', 'start' => '08:55', 'end' => '09:35'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '09:35', 'end' => '09:50'],
                    ['mapel' => 'PJOK', 'guru' => 'Riva Riana, S.Pd', 'start' => '09:50', 'end' => '10:30'],
                    ['mapel' => 'PJOK', 'guru' => 'Riva Riana, S.Pd', 'start' => '10:30', 'end' => '11:10'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '11:10', 'end' => '11:50'],
                    ['mapel' => 'DZH', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:50', 'end' => '12:30'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '12:30', 'end' => '13:00'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '13:00', 'end' => '13:40'],
                    ['mapel' => 'TKD', 'guru' => 'Riva Riana, S.Pd', 'start' => '13:40', 'end' => '14:20'],
                    ['mapel' => 'TKD', 'guru' => 'Riva Riana, S.Pd', 'start' => '14:20', 'end' => '15:00'],
                    ['mapel' => 'BTQ', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '15:00', 'end' => '15:20'],
                    ['mapel' => 'ASHR_SMP', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '15:20', 'end' => '15:30'],
                ],
                'Selasa' => [
                    ['mapel' => 'DHUHA', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:00', 'end' => '07:30'],
                    ['mapel' => 'IPA', 'guru' => 'Riva Riana, S.Pd', 'start' => '07:30', 'end' => '08:10'],
                    ['mapel' => 'IPA', 'guru' => 'Riva Riana, S.Pd', 'start' => '08:10', 'end' => '08:50'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '08:50', 'end' => '09:05'],
                    ['mapel' => 'PBL', 'guru' => 'Vika Wati Dzulciha, S.Ag', 'start' => '09:05', 'end' => '09:45'],
                    ['mapel' => 'PBL', 'guru' => 'Vika Wati Dzulciha, S.Ag', 'start' => '09:45', 'end' => '10:25'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '10:25', 'end' => '11:05'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '11:05', 'end' => '11:45'],
                    ['mapel' => 'DZH', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:45', 'end' => '12:30'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '12:30', 'end' => '13:00'],
                    ['mapel' => 'B.IND', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '13:00', 'end' => '13:40'],
                    ['mapel' => 'IPS', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '13:40', 'end' => '14:20'],
                    ['mapel' => 'IPS', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '14:20', 'end' => '15:00'],
                    ['mapel' => 'BTQ', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '15:00', 'end' => '15:20'],
                    ['mapel' => 'ASHR_SMP', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '15:20', 'end' => '15:30'],
                ],
                'Rabu' => [
                    ['mapel' => 'DHUHA', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:00', 'end' => '07:30'],
                    ['mapel' => 'PRM', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:30', 'end' => '09:00'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '09:00', 'end' => '09:15'],
                    ['mapel' => 'B.IND', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '09:15', 'end' => '09:55'],
                    ['mapel' => 'B.IND', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '09:55', 'end' => '10:35'],
                    ['mapel' => 'ING', 'guru' => 'Irnika Widiyan Dini, S.Li', 'start' => '10:35', 'end' => '11:15'],
                    ['mapel' => 'ING', 'guru' => 'Irnika Widiyan Dini, S.Li', 'start' => '11:15', 'end' => '11:55'],
                    ['mapel' => 'DZH', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:55', 'end' => '12:30'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '12:30', 'end' => '13:00'],
                    ['mapel' => 'B.IND', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '13:00', 'end' => '13:40'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '13:40', 'end' => '14:20'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '14:20', 'end' => '15:00'],
                    ['mapel' => 'BTQ', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '15:00', 'end' => '15:20'],
                    ['mapel' => 'ASHR_SMP', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '15:20', 'end' => '15:30'],
                ],
                'Kamis' => [
                    ['mapel' => 'DHUHA', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:00', 'end' => '07:30'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '07:30', 'end' => '08:10'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '08:10', 'end' => '08:50'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '08:50', 'end' => '09:05'],
                    ['mapel' => 'MTK', 'guru' => 'Ajeng Putyri Aryantika, S.Pd', 'start' => '09:05', 'end' => '09:45'],
                    ['mapel' => 'MTK', 'guru' => 'Ajeng Putyri Aryantika, S.Pd', 'start' => '09:45', 'end' => '10:25'],
                    ['mapel' => 'ARB', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '10:25', 'end' => '11:05'],
                    ['mapel' => 'ARB', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '11:05', 'end' => '11:45'],
                    ['mapel' => 'DZH', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:45', 'end' => '12:30'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '12:30', 'end' => '13:00'],
                    ['mapel' => 'IPA', 'guru' => 'Riva Riana, S.Pd', 'start' => '13:00', 'end' => '13:40'],
                    ['mapel' => 'AQD', 'guru' => 'Nurhayati, S.Ag', 'start' => '13:40', 'end' => '14:20'],
                    ['mapel' => 'AQD', 'guru' => 'Nurhayati, S.Ag', 'start' => '14:20', 'end' => '15:00'],
                    ['mapel' => 'BTQ', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '15:00', 'end' => '15:20'],
                    ['mapel' => 'ASHR_SMP', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '15:20', 'end' => '15:30'],
                ],
                'Jumat' => [
                    ['mapel' => 'DHUHA', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:00', 'end' => '07:30'],
                    ['mapel' => 'BPI', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:30', 'end' => '08:30'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '08:30', 'end' => '09:10'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '09:10', 'end' => '09:50'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '09:50', 'end' => '10:05'],
                    ['mapel' => 'FQH', 'guru' => 'Nurhayati, S.Ag', 'start' => '10:05', 'end' => '10:45'],
                    ['mapel' => 'FQH', 'guru' => 'Nurhayati, S.Ag', 'start' => '10:45', 'end' => '11:15'],
                    ['mapel' => 'DZH', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:15', 'end' => '11:30'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:30', 'end' => '13:00'],
                    ['mapel' => 'ING', 'guru' => 'Irnika Widiyan Dini, S.Li', 'start' => '13:00', 'end' => '13:40'],
                    ['mapel' => 'ING', 'guru' => 'Irnika Widiyan Dini, S.Li', 'start' => '13:40', 'end' => '14:20'],
                ],
            ],
            '8B' => [
                'Senin' => [
                    ['mapel' => 'DHUHA', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:00', 'end' => '07:30'],
                    ['mapel' => 'UPCR_SMP', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:30', 'end' => '08:15'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '08:15', 'end' => '08:55'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '08:55', 'end' => '09:35'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '09:35', 'end' => '09:50'],
                    ['mapel' => 'ING', 'guru' => 'Irnika Widiyan Dini, S.Li', 'start' => '09:50', 'end' => '10:30'],
                    ['mapel' => 'ING', 'guru' => 'Irnika Widiyan Dini, S.Li', 'start' => '10:30', 'end' => '11:10'],
                    ['mapel' => 'FQH', 'guru' => 'Nurhayati, S.Ag', 'start' => '11:10', 'end' => '11:50'],
                    ['mapel' => 'DZH', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:50', 'end' => '12:30'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '12:30', 'end' => '13:00'],
                    ['mapel' => 'FQH', 'guru' => 'Nurhayati, S.Ag', 'start' => '13:00', 'end' => '13:40'],
                    ['mapel' => 'PJOK', 'guru' => 'Riva Riana, S.Pd', 'start' => '13:40', 'end' => '14:20'],
                    ['mapel' => 'PJOK', 'guru' => 'Riva Riana, S.Pd', 'start' => '14:20', 'end' => '15:00'],
                    ['mapel' => 'BTQ', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '15:00', 'end' => '15:20'],
                    ['mapel' => 'ASHR_SMP', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '15:20', 'end' => '15:30'],
                ],
                'Selasa' => [
                    ['mapel' => 'DHUHA', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:00', 'end' => '07:30'],
                    ['mapel' => 'PBL', 'guru' => 'Vika Wati Dzulciha, S.Ag', 'start' => '07:30', 'end' => '08:10'],
                    ['mapel' => 'PBL', 'guru' => 'Vika Wati Dzulciha, S.Ag', 'start' => '08:10', 'end' => '08:50'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '08:50', 'end' => '09:05'],
                    ['mapel' => 'IPS', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '09:05', 'end' => '09:45'],
                    ['mapel' => 'IPS', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '09:45', 'end' => '10:25'],
                    ['mapel' => 'B.IND', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '10:25', 'end' => '11:05'],
                    ['mapel' => 'B.IND', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '11:05', 'end' => '11:45'],
                    ['mapel' => 'DZH', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:45', 'end' => '12:30'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '12:30', 'end' => '13:00'],
                    ['mapel' => 'AQD', 'guru' => 'Nurhayati, S.Ag', 'start' => '13:00', 'end' => '13:40'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '13:40', 'end' => '14:20'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '14:20', 'end' => '15:00'],
                    ['mapel' => 'BTQ', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '15:00', 'end' => '15:20'],
                    ['mapel' => 'ASHR_SMP', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '15:20', 'end' => '15:30'],
                ],
                'Rabu' => [
                    ['mapel' => 'DHUHA', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:00', 'end' => '07:30'],
                    ['mapel' => 'PRM', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:30', 'end' => '09:00'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '09:00', 'end' => '09:15'],
                    ['mapel' => 'IPA', 'guru' => 'Riva Riana, S.Pd', 'start' => '09:15', 'end' => '09:55'],
                    ['mapel' => 'IPA', 'guru' => 'Riva Riana, S.Pd', 'start' => '09:55', 'end' => '10:35'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '10:35', 'end' => '11:15'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '11:15', 'end' => '11:55'],
                    ['mapel' => 'DZH', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:55', 'end' => '12:30'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '12:30', 'end' => '13:00'],
                    ['mapel' => 'MTK', 'guru' => 'Ajeng Putyri Aryantika, S.Pd', 'start' => '13:00', 'end' => '13:40'],
                    ['mapel' => 'MTK', 'guru' => 'Ajeng Putyri Aryantika, S.Pd', 'start' => '13:40', 'end' => '14:20'],
                    ['mapel' => 'AQD', 'guru' => 'Nurhayati, S.Ag', 'start' => '14:20', 'end' => '15:00'],
                    ['mapel' => 'BTQ', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '15:00', 'end' => '15:20'],
                    ['mapel' => 'ASHR_SMP', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '15:20', 'end' => '15:30'],
                ],
                'Kamis' => [
                    ['mapel' => 'DHUHA', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:00', 'end' => '07:30'],
                    ['mapel' => 'B.IND', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '07:30', 'end' => '08:10'],
                    ['mapel' => 'B.IND', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '08:10', 'end' => '08:50'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '08:50', 'end' => '09:05'],
                    ['mapel' => 'ING', 'guru' => 'Irnika Widiyan Dini, S.Li', 'start' => '09:05', 'end' => '09:45'],
                    ['mapel' => 'ING', 'guru' => 'Irnika Widiyan Dini, S.Li', 'start' => '09:45', 'end' => '10:25'],
                    ['mapel' => 'IPA', 'guru' => 'Riva Riana, S.Pd', 'start' => '10:25', 'end' => '11:05'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '11:05', 'end' => '11:45'],
                    ['mapel' => 'DZH', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:45', 'end' => '12:30'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '12:30', 'end' => '13:00'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '13:00', 'end' => '13:40'],
                    ['mapel' => 'TKD', 'guru' => 'Riva Riana, S.Pd', 'start' => '13:40', 'end' => '14:20'],
                    ['mapel' => 'TKD', 'guru' => 'Riva Riana, S.Pd', 'start' => '14:20', 'end' => '15:00'],
                    ['mapel' => 'BTQ', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '15:00', 'end' => '15:20'],
                    ['mapel' => 'ASHR_SMP', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '15:20', 'end' => '15:30'],
                ],
                'Jumat' => [
                    ['mapel' => 'DHUHA', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:00', 'end' => '07:30'],
                    ['mapel' => 'BPI', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:30', 'end' => '08:30'],
                    ['mapel' => 'ARB', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '08:30', 'end' => '09:10'],
                    ['mapel' => 'ARB', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '09:10', 'end' => '09:50'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '09:50', 'end' => '10:05'],
                    ['mapel' => 'MTK', 'guru' => 'Ajeng Putyri Aryantika, S.Pd', 'start' => '10:05', 'end' => '10:45'],
                    ['mapel' => 'MTK', 'guru' => 'Ajeng Putyri Aryantika, S.Pd', 'start' => '10:45', 'end' => '11:15'],
                    ['mapel' => 'DZH', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:15', 'end' => '11:30'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:30', 'end' => '13:00'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '13:00', 'end' => '13:40'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '13:40', 'end' => '14:20'],
                ],
            ],
            '9A' => [
                'Senin' => [
                    ['mapel' => 'DHUHA', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:00', 'end' => '07:30'],
                    ['mapel' => 'UPCR_SMP', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:30', 'end' => '08:15'],
                    ['mapel' => 'IPA', 'guru' => 'Riva Riana, S.Pd', 'start' => '08:15', 'end' => '08:55'],
                    ['mapel' => 'IPA', 'guru' => 'Riva Riana, S.Pd', 'start' => '08:55', 'end' => '09:35'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '09:35', 'end' => '09:50'],
                    ['mapel' => 'IPS', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '09:50', 'end' => '10:30'],
                    ['mapel' => 'IPS', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '10:30', 'end' => '11:10'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '11:10', 'end' => '11:50'],
                    ['mapel' => 'DZH', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:50', 'end' => '12:30'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '12:30', 'end' => '13:00'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '13:00', 'end' => '13:40'],
                    ['mapel' => 'B.IND', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '13:40', 'end' => '14:20'],
                    ['mapel' => 'B.IND', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '14:20', 'end' => '15:00'],
                    ['mapel' => 'BTQ', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '15:00', 'end' => '15:20'],
                    ['mapel' => 'ASHR_SMP', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '15:20', 'end' => '15:30'],
                ],
                'Selasa' => [
                    ['mapel' => 'DHUHA', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:00', 'end' => '07:30'],
                    ['mapel' => 'MTK', 'guru' => 'Ajeng Putyri Aryantika, S.Pd', 'start' => '07:30', 'end' => '08:10'],
                    ['mapel' => 'MTK', 'guru' => 'Ajeng Putyri Aryantika, S.Pd', 'start' => '08:10', 'end' => '08:50'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '08:50', 'end' => '09:05'],
                    ['mapel' => 'B.IND', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '09:05', 'end' => '09:45'],
                    ['mapel' => 'B.IND', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '09:45', 'end' => '10:25'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '10:25', 'end' => '11:05'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '11:05', 'end' => '11:45'],
                    ['mapel' => 'DZH', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:45', 'end' => '12:30'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '12:30', 'end' => '13:00'],
                    ['mapel' => 'KTI', 'guru' => 'Sahrial Pulungan, M.Pd', 'start' => '13:00', 'end' => '13:40'],
                    ['mapel' => 'KTI', 'guru' => 'Sahrial Pulungan, M.Pd', 'start' => '13:40', 'end' => '14:20'],
                    ['mapel' => 'ING', 'guru' => 'Irnika Widiyan Dini, S.Li', 'start' => '14:20', 'end' => '15:00'],
                    ['mapel' => 'BTQ', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '15:00', 'end' => '15:20'],
                    ['mapel' => 'ASHR_SMP', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '15:20', 'end' => '15:30'],
                ],
                'Rabu' => [
                    ['mapel' => 'DHUHA', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:00', 'end' => '07:30'],
                    ['mapel' => 'PRM', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:30', 'end' => '09:00'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '09:00', 'end' => '09:15'],
                    ['mapel' => 'PJOK', 'guru' => 'Riva Riana, S.Pd', 'start' => '09:15', 'end' => '09:55'],
                    ['mapel' => 'PJOK', 'guru' => 'Riva Riana, S.Pd', 'start' => '09:55', 'end' => '10:35'],
                    ['mapel' => 'TKD', 'guru' => 'Riva Riana, S.Pd', 'start' => '10:35', 'end' => '11:15'],
                    ['mapel' => 'TKD', 'guru' => 'Riva Riana, S.Pd', 'start' => '11:15', 'end' => '11:55'],
                    ['mapel' => 'DZH', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:55', 'end' => '12:30'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '12:30', 'end' => '13:00'],
                    ['mapel' => 'ING', 'guru' => 'Irnika Widiyan Dini, S.Li', 'start' => '13:00', 'end' => '13:40'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '13:40', 'end' => '14:20'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '14:20', 'end' => '15:00'],
                    ['mapel' => 'BTQ', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '15:00', 'end' => '15:20'],
                    ['mapel' => 'ASHR_SMP', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '15:20', 'end' => '15:30'],
                ],
                'Kamis' => [
                    ['mapel' => 'DHUHA', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:00', 'end' => '07:30'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '07:30', 'end' => '08:10'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '08:10', 'end' => '08:50'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '08:50', 'end' => '09:05'],
                    ['mapel' => 'PAI', 'guru' => 'Nurhayati, S.Ag', 'start' => '09:05', 'end' => '09:45'],
                    ['mapel' => 'PAI', 'guru' => 'Nurhayati, S.Ag', 'start' => '09:45', 'end' => '10:25'],
                    ['mapel' => 'MTK', 'guru' => 'Ajeng Putyri Aryantika, S.Pd', 'start' => '10:25', 'end' => '11:05'],
                    ['mapel' => 'MTK', 'guru' => 'Ajeng Putyri Aryantika, S.Pd', 'start' => '11:05', 'end' => '11:45'],
                    ['mapel' => 'DZH', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:45', 'end' => '12:30'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '12:30', 'end' => '13:00'],
                    ['mapel' => 'KT', 'guru' => 'Sahrial Pulungan, M.Pd', 'start' => '13:00', 'end' => '13:40'],
                    ['mapel' => 'ING', 'guru' => 'Irnika Widiyan Dini, S.Li', 'start' => '13:40', 'end' => '14:20'],
                    ['mapel' => 'ING', 'guru' => 'Irnika Widiyan Dini, S.Li', 'start' => '14:20', 'end' => '15:00'],
                    ['mapel' => 'BTQ', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '15:00', 'end' => '15:20'],
                    ['mapel' => 'ASHR_SMP', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '15:20', 'end' => '15:30'],
                ],
                'Jumat' => [
                    ['mapel' => 'DHUHA', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:00', 'end' => '07:30'],
                    ['mapel' => 'BPI', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:30', 'end' => '08:30'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '08:30', 'end' => '09:10'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '09:10', 'end' => '09:50'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '09:50', 'end' => '10:05'],
                    ['mapel' => 'ING', 'guru' => 'Irnika Widiyan Dini, S.Li', 'start' => '10:05', 'end' => '10:45'],
                    ['mapel' => 'ING', 'guru' => 'Irnika Widiyan Dini, S.Li', 'start' => '10:45', 'end' => '11:15'],
                    ['mapel' => 'DZH', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:15', 'end' => '11:30'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:30', 'end' => '13:00'],
                    ['mapel' => 'ARB', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '13:00', 'end' => '13:40'],
                    ['mapel' => 'ARB', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '13:40', 'end' => '14:20'],
                ],
            ],
            '9B' => [
                'Senin' => [
                    ['mapel' => 'DHUHA', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:00', 'end' => '07:30'],
                    ['mapel' => 'UPCR_SMP', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:30', 'end' => '08:15'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '08:15', 'end' => '08:55'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '08:55', 'end' => '09:35'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '09:35', 'end' => '09:50'],
                    ['mapel' => 'IPA', 'guru' => 'Riva Riana, S.Pd', 'start' => '09:50', 'end' => '10:30'],
                    ['mapel' => 'IPA', 'guru' => 'Riva Riana, S.Pd', 'start' => '10:30', 'end' => '11:10'],
                    ['mapel' => 'B.IND', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '11:10', 'end' => '11:50'],
                    ['mapel' => 'DZH', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:50', 'end' => '12:30'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '12:30', 'end' => '13:00'],
                    ['mapel' => 'B.IND', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '13:00', 'end' => '13:40'],
                    ['mapel' => 'PAI', 'guru' => 'Nurhayati, S.Ag', 'start' => '13:40', 'end' => '14:20'],
                    ['mapel' => 'PAI', 'guru' => 'Nurhayati, S.Ag', 'start' => '14:20', 'end' => '15:00'],
                    ['mapel' => 'BTQ', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '15:00', 'end' => '15:20'],
                    ['mapel' => 'ASHR_SMP', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '15:20', 'end' => '15:30'],
                ],
                'Selasa' => [
                    ['mapel' => 'DHUHA', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:00', 'end' => '07:30'],
                    ['mapel' => 'ARB', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '07:30', 'end' => '08:10'],
                    ['mapel' => 'ARB', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '08:10', 'end' => '08:50'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '08:50', 'end' => '09:05'],
                    ['mapel' => 'MTK', 'guru' => 'Ajeng Putyri Aryantika, S.Pd', 'start' => '09:05', 'end' => '09:45'],
                    ['mapel' => 'MTK', 'guru' => 'Ajeng Putyri Aryantika, S.Pd', 'start' => '09:45', 'end' => '10:25'],
                    ['mapel' => 'ING', 'guru' => 'Irnika Widiyan Dini, S.Li', 'start' => '10:25', 'end' => '11:05'],
                    ['mapel' => 'IPS', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:05', 'end' => '11:45'],
                    ['mapel' => 'DZH', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:45', 'end' => '12:30'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '12:30', 'end' => '13:00'],
                    ['mapel' => 'IPS', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '13:00', 'end' => '13:40'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '13:40', 'end' => '14:20'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '14:20', 'end' => '15:00'],
                    ['mapel' => 'BTQ', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '15:00', 'end' => '15:20'],
                    ['mapel' => 'ASHR_SMP', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '15:20', 'end' => '15:30'],
                ],
                'Rabu' => [
                    ['mapel' => 'DHUHA', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:00', 'end' => '07:30'],
                    ['mapel' => 'PRM', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:30', 'end' => '09:00'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '09:00', 'end' => '09:15'],
                    ['mapel' => 'ING', 'guru' => 'Irnika Widiyan Dini, S.Li', 'start' => '09:15', 'end' => '09:55'],
                    ['mapel' => 'ING', 'guru' => 'Irnika Widiyan Dini, S.Li', 'start' => '09:55', 'end' => '10:35'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '10:35', 'end' => '11:15'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '11:15', 'end' => '11:55'],
                    ['mapel' => 'DZH', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:55', 'end' => '12:30'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '12:30', 'end' => '13:00'],
                    ['mapel' => 'KT', 'guru' => 'Sahrial Pulungan, M.Pd', 'start' => '13:00', 'end' => '13:40'],
                    ['mapel' => 'PJOK', 'guru' => 'Riva Riana, S.Pd', 'start' => '13:40', 'end' => '14:20'],
                    ['mapel' => 'PJOK', 'guru' => 'Riva Riana, S.Pd', 'start' => '14:20', 'end' => '15:00'],
                    ['mapel' => 'BTQ', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '15:00', 'end' => '15:20'],
                    ['mapel' => 'ASHR_SMP', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '15:20', 'end' => '15:30'],
                ],
                'Kamis' => [
                    ['mapel' => 'DHUHA', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:00', 'end' => '07:30'],
                    ['mapel' => 'MTK', 'guru' => 'Ajeng Putyri Aryantika, S.Pd', 'start' => '07:30', 'end' => '08:10'],
                    ['mapel' => 'MTK', 'guru' => 'Ajeng Putyri Aryantika, S.Pd', 'start' => '08:10', 'end' => '08:50'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '08:50', 'end' => '09:05'],
                    ['mapel' => 'B.IND', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '09:05', 'end' => '09:45'],
                    ['mapel' => 'B.IND', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '09:45', 'end' => '10:25'],
                    ['mapel' => 'ING', 'guru' => 'Irnika Widiyan Dini, S.Li', 'start' => '10:25', 'end' => '11:05'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '11:05', 'end' => '11:45'],
                    ['mapel' => 'DZH', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:45', 'end' => '12:30'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '12:30', 'end' => '13:00'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '13:00', 'end' => '13:40'],
                    ['mapel' => 'KTI', 'guru' => 'Sahrial Pulungan, M.Pd', 'start' => '13:40', 'end' => '14:20'],
                    ['mapel' => 'KTI', 'guru' => 'Sahrial Pulungan, M.Pd', 'start' => '14:20', 'end' => '15:00'],
                    ['mapel' => 'BTQ', 'guru' => 'Adinda Oktavhiani S.Pd', 'start' => '15:00', 'end' => '15:20'],
                    ['mapel' => 'ASHR_SMP', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '15:20', 'end' => '15:30'],
                ],
                'Jumat' => [
                    ['mapel' => 'DHUHA', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:00', 'end' => '07:30'],
                    ['mapel' => 'BPI', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '07:30', 'end' => '08:30'],
                    ['mapel' => 'ING', 'guru' => 'Irnika Widiyan Dini, S.Li', 'start' => '08:30', 'end' => '09:10'],
                    ['mapel' => 'ING', 'guru' => 'Irnika Widiyan Dini, S.Li', 'start' => '09:10', 'end' => '09:50'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '09:50', 'end' => '10:05'],
                    ['mapel' => 'TKD', 'guru' => 'Riva Riana, S.Pd', 'start' => '10:05', 'end' => '10:45'],
                    ['mapel' => 'TKD', 'guru' => 'Riva Riana, S.Pd', 'start' => '10:45', 'end' => '11:15'],
                    ['mapel' => 'DZH', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:15', 'end' => '11:30'],
                    ['mapel' => 'IST', 'guru' => 'Sri Wanti Maulani, S.Pd', 'start' => '11:30', 'end' => '13:00'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '13:00', 'end' => '13:40'],
                    ['mapel' => 'TAH', 'guru' => 'Intan Kusuma Dera, S.Ag', 'start' => '13:40', 'end' => '14:20'],
                ],
            ],
        ];
        $semuaJadwal = $jadwalPerKelasSmp ?? [];
        foreach ($semuaJadwal as $kodeKelas => $hariMap) {
            $kelas = Kelas::query()->where('nama_kelas', $kodeKelas)->orWhere('kode_kelas', $kodeKelas)->first();
            if ($kelas) {
                foreach ($hariMap as $hari => $items) {
                    foreach ($items as $item) {
                        $mapel = Mapel::query()->where('kode', $item['mapel'])->first();
                        $guru = Guru::query()->where('nama', $item['guru'])->first();
                        if ($mapel && $guru) {
                            Jadwal::updateOrCreate(
                                [
                                    'kelas_id' => $kelas->id,
                                    'hari' => $hari,
                                    'jam_mulai' => $item['start']
                                ],
                                [
                                    'mapel_id' => $mapel->id,
                                    'guru_id' => $guru->id,
                                    'jam_selesai' => $item['end']
                                ]
                            );
                        } else {
                            $missing = [];
                            if (!$mapel) $missing[] = "Mapel '{$item['mapel']}'";
                            if (!$guru) $missing[] = "Guru '{$item['guru']}'";
                            $msg = implode(" & ", $missing);
                            echo "Peringatan: Jadwal Kelas {$kodeKelas} Hari {$hari} gagal dimasukkan karena {$msg} tidak ditemukan di database!\n";
                        }
                    }
                }
            } else {
                echo "Peringatan: Kelas '{$kodeKelas}' tidak ditemukan!\n";
            }
        }
    }
}
